## **Chapter 2: TensorFlow**


### **Ex1: Constants, Sequences, và Random Values**
*Constant Value Tensors*
- Câu 1: Tạo một tensor có shape [2, 3] với tất cả các phần tử ban đầu = 0
- Câu 2: Cho X là một tensor như sau [[1,2,3], [4,5,6]]. Tạo 1 tensor có cùng shape và dtype
như X với các phần tử ban đầu = 0
- Câu 3: Tạo một tensor có shape [2, 3] với tất cả các phần tử ban đầu là 1
- Câu 4: Cho X là một tensor như sau [[1,2,3], [4,5,6]]. Tạo 1 tensor có cùng shape và dtype
như X với các phần tử ban đầu = 1
- Câu 5: Tạo một tensor có shape [3, 2] với tất cả các phần tử ban đầu là 5
- Câu 6: Tạo một constant tensor [[1, 3, 5], [4, 6, 8]], dtype=float32
- Câu 7: Tạo một constant tensor có shape [2, 3], với tất cả các phần tử ban đầu là 4

In [2]:
import tensorflow as tf

In [9]:
import numpy as np

In [8]:
# Câu 1: Tạo một tensor có shape [2, 3] với tất cả các phần tử ban đầu = 0
tf1 = tf.fill(dims = [2,3], value = 0)  # <=> tf.zeros([2, 3])
tf.print(tf1)

[[0 0 0]
 [0 0 0]]


In [11]:
# Câu 2: Cho X là một tensor như sau [[1,2,3], [4,5,6]]. 
# Tạo 1 tensor có cùng shape và dtype như X với các phần tử ban đầu = 0
X_np = np.array([[1,2,3], [4,5,6]])
X = tf.convert_to_tensor(X_np)

tf2 = tf.zeros_like(X)
tf.print(tf2)

[[0 0 0]
 [0 0 0]]


In [12]:
# Câu 3: Tạo một tensor có shape [2, 3] với tất cả các phần tử ban đầu là 1
tf3 = tf.fill(value = 1, dims = [2,3]) # <=> tf.ones([2, 3])
tf.print(tf3)

[[1 1 1]
 [1 1 1]]


In [14]:
# Câu 4: Cho X là một tensor như sau [[1,2,3], [4,5,6]]. 
# Tạo 1 tensor có cùng shape và dtype như X với các phần tử ban đầu = 1
X_np = np.array([[1,2,3], [4,5,6]])
X = tf.convert_to_tensor(X_np)

tf4 = tf.ones_like(X)
tf.print(tf4)

[[1 1 1]
 [1 1 1]]


In [18]:
# Câu 5: Tạo một tensor có shape [3, 2] với tất cả các phần tử ban đầu là 5
tf5 = tf.fill(dims = [3,2], value = 5)
tf.print(tf5)

[[5 5]
 [5 5]
 [5 5]]


In [20]:
# Câu 6: Tạo một constant tensor [[1, 3, 5], [4, 6, 8]], dtype=float32
tf6 = tf.constant([[1, 3, 5], [4, 6, 8]], dtype=tf.float32)
tf.print(tf6)

[[1 3 5]
 [4 6 8]]


In [21]:
# Câu 7: Tạo một constant tensor có shape [2, 3], với tất cả các phần tử ban đầu là 4
tf7 = tf.constant(shape = [2,3], value = 4)
tf.print(tf7)

[[4 4 4]
 [4 4 4]]


### **Sequence**

**Câu 1: Tạo 1-D tensor gồm 50 phần tử khoảng cách đều nhau từ 5 đến 10**

In [5]:
out = tf.linspace(5, 10, 50)
tf.print(out)

[5 5.1020408163265305 5.204081632653061 ... 9.795918367346939 9.89795918367347 10]


**Câu 2: Tạo 1 tensor như sau: [10, 12, 14, 16, ...100]**

In [6]:
out = tf.range(10, 101, 2)
tf.print(out)

[10 12 14 ... 96 98 100]


### **Random Tensor**

**Câu 1: Tạo một tensor ngẫu nhiên có shape [3, 2], với các phần tử từ phân bố chuẩn của giá
trị trung bình = 0 (normal distribution of mean), độ lệch chuẩn = 2 (standard deviation)**

In [9]:
x = tf.random.normal([3,2], mean = 0, stddev = 2)
tf.print(x)

[[0.184808224 -3.37327456]
 [3.09447813 -1.06402099]
 [0.429784268 -2.4607656]]


**Câu 2: Tạo một random tensor có shape [3, 2], với các phần tử nằm trong một uniform
distribution trong khoảng từ 0 đến 2.**

In [22]:
y = tf.random.uniform([3, 2], 0, 2)
tf.print(y)

[[0.514561176 0.436234951]
 [1.21841216 1.32176781]
 [1.64169979 0.21726656]]
